final doctorMapList = [
  {
    "name": "Dr. Johnson",
    "type": "Encok/keseleo",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/dralexjonson.png",
    "description": "Kamu encok? kami tabrak, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Jefry",
    "type": "Neurology",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/drjefrymando.png",
    "description": "Pelayanan ku mantap toh mas, soal rasa sakit tak pernah bohong, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "DR. Benny",
    "type": "Physikolog",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image":"assets/dralexanderbenny.png",
    "description": "Kena mental? sini selfie aja dulu, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Susanto",
    "type": "Dokter Gigi",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image":"assets/drsusanto.png",
    "description": "Sini bayar dulu baru saya cabut giginya, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  }
];
